server:
  port: 7000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atcrowdfunding?serverTimezone=GMT%2b8
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource





eureka:
  client:
    service-url:
      defaultZone:http://localhost:8761/eureka
mybatis:
  mapper-locations: classpath:com/offcn/user/mapper
  config-location: classpath:mybatis/mybatis-config.xml

